Repository 42connected/polar-fe, pull requests merged in 2022-11, with the labels that each got.

#362 Fix: 보고서 여러 개 출력시 페이지가 밀리는 것 수정
  src/containers/report-detail/report-detail.tsx
  src/containers/report-detail/reportStyled.tsx
Labels: bug

#364 [Fix] data-room 정렬 버그, 멘토 상세 드래그 가능
  src/components/data-room/search-box.tsx
  src/containers/data-room/data-room-list.tsx
  src/containers/data-room/data-room.tsx
  src/containers/my-mentoring-mentor/my-mentoring-mentor.tsx
Labels: bug

#366 Fix: report-detail 일정 글자 이상 폰트 조절 변경
  src/containers/report-detail/report-detail.tsx
  src/containers/report-detail/reportStyled.tsx
Labels: Bug 🚨

#371 Fix: 보고서 페이지 프린터 페이지 밀림 현상 수정
  src/containers/report-detail/report-detail.tsx
  src/containers/report-detail/reportStyled.tsx
Labels: Bug 🚨

#382 [Feature] recoil #378
  package-lock.json
  package.json
  src/components/common/Providers.tsx
  src/recoil/atoms/index.ts
  src/recoil/atoms/modalAtom.ts
  tsconfig.paths.json
Labels: Enhancement ✨

#384 Hotfix/#375 reportdetail styled bug
  .DS_Store
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactoring.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/containers/report-detail/report-detail.tsx
  src/containers/report-detail/reportStyled.tsx
Labels: Bug 🚨

#388 fix: 로고 변경(hotfix/#387-chang_log_on_nav) #387
  src/assets/image/logo/logoNew.png
  src/assets/image/logo/logoNew2.png
  src/assets/image/logo/logoNew3.png
  src/assets/image/logo/logoNew4.png
  src/assets/image/logo/logoNew5.png
  src/assets/image/logo/logoNew6.png
  src/components/header/header.tsx
Labels: High 🥇, Refactor 🌈

#391 Fix: componentV2 최신화 #369
  src/components/v2/common/Button.tsx
  src/components/v2/common/modal/ConfirmModal.tsx
  src/components/v2/common/modal/DetailModal.tsx
  src/components/v2/common/modal/ErrorModal.tsx
  src/components/v2/common/modal/GuideModal.tsx
  src/components/v2/common/modal/ModalBox.tsx
  src/components/v2/common/modal/ModalInfoRow.tsx
  src/components/v2/common/modal/ModalInputBox.tsx
  src/components/v2/common/modal/StatusButton.tsx
Labels: Enhancement ✨

#394 [Refactor] 파비콘 로고 변경 및 임시 배포 스크립트 추가
  .DS_Store
  package.json
  public/logo.ico
Labels: Medium 🥈, Refactor 🌈
